version: '3'

services:

  robohash_node:
      image: robohash:latest
      restart: always
      ports:
          - 8082:8080
      deploy:
          replicas: 1
      working_dir: /usr/src/app
      environment:
          PORT: "8080"

